### ISSUE TITLE
Bezier Curve Editor in Morphic

### ISSUE THREAD

**Issue by tom95** [HPI-SWA-Lab/BP2016H1#41]
A simple editor for a single bezier curve where every control element is represented as a morph.

**Comment by corinnaj** [comment]
Figure out how to redraw, after a Morph was dropped. http://wiki.squeak.org/squeak/6194 (maybe it is #acceptDroppingMorph)

**Comment by marceltaeumel** [comment]
If you model a control point as a separate morph, you might want to move it like this:

```Smalltalk
... Morph subclass: #MyControlPoint ...

MyControlPoint >> #handlesMouseDown: evt
   ^ true

MyControlPoint >> #mouseDown: evt
   ref := self topLeft - evt position.

MyControlPoint >> #mouseMove: evt
   self topLeft: evt position - ref.
```

Otherwise, dragging means attaching it to the hand. For this, use `HandMorph >> #grabMorph:` instead of `#addMorph:` because of the call-backs. It is usually started in `Morph >> #startDrag:`, but you can use any other call-back. Initiate drag for the standard call-backs like this:

```Smalltalk
MyControlPoint >> #mouseDown: evt
   evt hand waitForClicksOrDrag: self event: evt.
```

Dropping a morph into another morph is handled in `Morph >> #handleDropMorph:` and involves the following call-backs:

```Smalltalk
Morph >> #wantsDroppedMorph:event:
Morph >> #wantsToBeDroppedInto:
Morph >> #acceptDroppingMorph:event:
Morph >> #justDroppedInto:event:
```

The containment change (i.e. `#addMorph:`) should be implemented in `#acceptDroppingMorph:event:`.

In all these cases, re-drawing should happen automatically because of `#topLeft:` and `#addMorph:`. They all call `Morph >> #changed` eventually.

**Comment by ekrebs5** [comment]
now works for one bezier curve with start-, end- and 2 controlpoints

ideas for possible additions (can also be researched):
- curve with more points
- special curve(s) for circels etc
- "auto correct" the transition between two curves
- use it to model glyph outlines

**Comment by corinnaj** [comment]
Goal of spike has been fulfilled, might be reopened later if we choose to continue in this direction
